services:
  web-app:
    build: .
    container_name: petshop
    ports:
    - "8080:80"
    volumes:
    - ${PWD}:/var/www/html
    networks:
    - database
    - applications
networks:
  database:
    external: true
  applications:
    external: true